name: app
type: golang:1.14
hooks:
    build: |    
        ./npm
relationships:
    database: "db:mysql"
web:
    upstream:
        socket_family: tcp
        protocol: http

    commands:
        start: ./bin/app

    locations:
        /:
            allow: false
            passthru: true

