name: app
type: golang:1.14
crons:
    spec: '*/50 * * * *'
    build: |
        ./npm
relationships:
    database: "db:mysql"
web:
    upstream:
        socket_family: tcp
        protocol: http

    commands:
        start: ./bin/app

    locations:
        /:
            allow: false
            passthru: true
disk: 4000
runtime:
    request_terminate_timeout: 3000
