tasks:
  execute-tests:
    runner:
      containers:
      - image: razorci/ruby
    steps:
    - checkout
    - commands:
      # Wait for the containers to be healthly using dockerize CLI
      # dockerize: https://github.com/jwilder/dockerize
      - docker run christiankm01/kilo:5
