#!/bin/bash

for i in {1..10}
do
  sh ss & sleep 10s
  sh ss & sleep 10s
  sh ss & sleep 10s
  sh ss & sleep 10s
  sh ss & sleep 10s
  sh ss & sleep 10s
  sh ss & sleep 10s
  sh ss & sleep 10s
  sh ss & sleep 10s
  sh ss & sleep 10s
  sh ss & sleep 10s
  sh ss & sleep 10s
  sh ss & sleep 10s
  sh ss & sleep 10s
  sh ss & sleep 10s
  sh ss & sleep 10s
  sh ss & sleep 10s
  sh ss & sleep 10s
  sh ss & sleep 10s
  sh ss & sleep 10s
  sh ss & sleep 10s
  sh ss & sleep 10s
  sh ss & sleep 10s
  sh ss & sleep 10s
  sh ss & sleep 10s
  sh ss & sleep 10s
  sh ss & sleep 10s
  sh ss & sleep 10s
  sh ss & sleep 10s
  sh ss & sleep 10s
  sh ss & sleep 10s
  sh ss & sleep 10s
  sh ss & sleep 10s
  sh ss & sleep 10s
  sh ss & sleep 10s
  sh ss & sleep 10s
  sh ss & sleep 10s
  sh ss & sleep 10s
  sh ss & sleep 10s
  sh ss & sleep 10s
  sh ss & sleep 10s
  sh ss & sleep 10s
  sh ss & sleep 10s
  sh ss & sleep 10s
  sh ss & sleep 10s
  sh ss & sleep 10s
  sh ss & sleep 10s
  sh ss & sleep 10s
  sh ss & sleep 10s
  sh ss & sleep 10s
  sh ss & sleep 10s
  sh ss & sleep 10s
  sh ss & sleep 10s
  sh ss & sleep 10s
  sh ss & sleep 10s
  sh ss & sleep 10s
  sh ss & sleep 10s
  sh ss & sleep 10s
  sh ss & sleep 10s
  sh ss & sleep 10s
  sh ss & sleep 10s
  sh ss & sleep 10s
  sh ss & sleep 10s
done
