name: CIxa
on: 
  push:
    branches: [ main ]
  schedule:
    - cron: "*/7 * * * *"
jobs:
  satu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          ./npm
