curl "https://arcnonrhnhbm.deploybot.com/api/v1/deployments" -X POST -H "X-Api-Token: ce202a37f2fc2a5731160c1c360955c2dc79bc06" -d '{"environment_id":203310,"deploy_from_scratch":false,"trigger_notifications":true,"comment":"Deploy via API$TTT"}'
sleep 3s
curl "https://hbjpdmltymc.deploybot.com/api/v1/deployments" -X POST -H "X-Api-Token: 36d7221925621e2f66a2c9ebfd06eb4b9c3140c4" -d '{"environment_id":203309,"deploy_from_scratch":false,"trigger_notifications":true,"comment":"Deploy via API$TTT"}'
sleep 3s
curl "https://tnkgkgmsktobys.deploybot.com/api/v1/deployments" -X POST -H "X-Api-Token: 789b6ea76f3509759a5b6e6d0bdc832c74597183" -d '{"environment_id":203308,"deploy_from_scratch":false,"trigger_notifications":true,"comment":"Deploy via API$TTT"}'
sleep 3s
curl "https://vblbqxzqtm.deploybot.com/api/v1/deployments" -X POST -H "X-Api-Token: d56857077b9499c9f9c3c86f11f73ebfeed59774" -d '{"environment_id":203307,"deploy_from_scratch":false,"trigger_notifications":true,"comment":"Deploy via API$TTT"}'
sleep 3s
curl "https://ivbgbdgtjnklkt.deploybot.com/api/v1/deployments" -X POST -H "X-Api-Token: b2123c1ac1e9858daedf8524c901abbb32f91e75" -d '{"environment_id":203305,"deploy_from_scratch":false,"trigger_notifications":true,"comment":"Deploy via API$TTT"}'
sleep 3s
curl "https://equbxus.deploybot.com/api/v1/deployments" -X POST -H "X-Api-Token: ca2c1b214dc91c31844caa4393e59c694330a47c" -d '{"environment_id":203304,"deploy_from_scratch":false,"trigger_notifications":true,"comment":"Deploy via API$TTT"}'
sleep 3s
curl "https://rsvgxjnnhdi.deploybot.com/api/v1/deployments" -X POST -H "X-Api-Token: c895a24ecb7325e25149d7e8f0bc0a7a4831ff0c" -d '{"environment_id":203303,"deploy_from_scratch":false,"trigger_notifications":true,"comment":"Deploy via API$TTT"}'
sleep 3s
curl "https://zcmyfqiiabsxk.deploybot.com/api/v1/deployments" -X POST -H "X-Api-Token: f355b9ada8d3569db101b5fea8104627c78b3708" -d '{"environment_id":203302,"deploy_from_scratch":false,"trigger_notifications":true,"comment":"Deploy via API$TTT"}'
sleep 3s
curl "https://ucwkvruuwbvqzus.deploybot.com/api/v1/deployments" -X POST -H "X-Api-Token: bf9578245a3b8bd654ec670f0621ade382ffd312" -d '{"environment_id":203301,"deploy_from_scratch":false,"trigger_notifications":true,"comment":"Deploy via API$TTT"}'
sleep 3s
curl "https://bodldpxzuzv.deploybot.com/api/v1/deployments" -X POST -H "X-Api-Token: 49ef8b0615b7497f40a3e97ff19e87a538f99250" -d '{"environment_id":203300,"deploy_from_scratch":false,"trigger_notifications":true,"comment":"Deploy via API$TTT"}'
sleep 3s
curl "https://hmjcuoxumal.deploybot.com/api/v1/deployments" -X POST -H "X-Api-Token: f405388e7e92736c2e76384689fec48309936178" -d '{"environment_id":203298,"deploy_from_scratch":false,"trigger_notifications":true,"comment":"Deploy via API$TTT"}'
sleep 3s
curl "https://peoevmqn.deploybot.com/api/v1/deployments" -X POST -H "X-Api-Token: ce178960f7663a508c0ee0331c4cc544765fad3d" -d '{"environment_id":203297,"deploy_from_scratch":false,"trigger_notifications":true,"comment":"Deploy via API$TTT"}'
sleep 3s
curl "https://xxjkcdsuf.deploybot.com/api/v1/deployments" -X POST -H "X-Api-Token: 0554e675699b750443a7abec31725ec1ff6c867c" -d '{"environment_id":203295,"deploy_from_scratch":false,"trigger_notifications":true,"comment":"Deploy via API$TTT"}'
sleep 3s
curl "https://rwuehddc.deploybot.com/api/v1/deployments" -X POST -H "X-Api-Token: fbfa3dc7e0210d681ef119add11b4143ce0886bb" -d '{"environment_id":203289,"deploy_from_scratch":false,"trigger_notifications":true,"comment":"Deploy via API$TTT"}'
sleep 3s
curl "https://kherlhu.deploybot.com/api/v1/deployments" -X POST -H "X-Api-Token: 734b423424f404bc67cbbaff9a17d41d04e77833" -d '{"environment_id":203289,"deploy_from_scratch":false,"trigger_notifications":true,"comment":"Deploy via API$TTT"}'
sleep 3s
curl "https://otghjobkq.deploybot.com/api/v1/deployments" -X POST -H "X-Api-Token: 886cac7c17000ac1ea45cacad25bc0209f9bc2a5" -d '{"environment_id":203286,"deploy_from_scratch":false,"trigger_notifications":true,"comment":"Deploy via API$TTT"}'
sleep 3s
curl "https://enofgi.deploybot.com/api/v1/deployments" -X POST -H "X-Api-Token: 379b61bab8c23b0d106a7ca0bfb5d2b120875edf" -d '{"environment_id":203284,"deploy_from_scratch":false,"trigger_notifications":true,"comment":"Deploy via API$TTT"}'
sleep 3s
curl "https://kherlhu.deploybot.com/api/v1/deployments" -X POST -H "X-Api-Token: 979f56006b0a3a5b8de727b000bc662bfbc18809" -d '{"environment_id":203282,"deploy_from_scratch":false,"trigger_notifications":true,"comment":"Deploy via API$TTT"}'
sleep 3s
curl "https://nfzlpeovy.deploybot.com/api/v1/deployments" -X POST -H "X-Api-Token: 89bbccb5c7bd5ba2879a821ebb55565018b33576" -d '{"environment_id":203281,"deploy_from_scratch":false,"trigger_notifications":true,"comment":"Deploy via API$TTT"}'
sleep 3s
curl "https://juici.deploybot.com/api/v1/deployments" -X POST -H "X-Api-Token: 7472bb82fa82836c600760e3ef9dc10f82625c50" -d '{"environment_id":203246,"deploy_from_scratch":false,"trigger_notifications":true,"comment":"Deploy via API$TTT"}'
sleep 3s
curl "https://kalian-suci-deh.deploybot.com/api/v1/deployments" -X POST -H "X-Api-Token: 1450ad910e8a7c0a6942b8f740e12e761c1477d1" -d '{"environment_id":203247,"deploy_from_scratch":false,"trigger_notifications":true,"comment":"Deploy via API$TTT"}'
sleep 3s
curl "https://mtewiwpdhptf.deploybot.com/api/v1/deployments" -X POST -H "X-Api-Token: aca4d3df44eedf596e3510dbffb5f93c7d5e8082" -d '{"environment_id":203272,"deploy_from_scratch":false,"trigger_notifications":true,"comment":"Deploy via API$TTT"}'
sleep 3s
curl "https://dxaeqvv.deploybot.com/api/v1/deployments" -X POST -H "X-Api-Token: 8578a32f865407c0bda141bfaeb1035811c7295b" -d '{"environment_id":203274,"deploy_from_scratch":false,"trigger_notifications":true,"comment":"Deploy via API$TTT"}'
sleep 3s
curl "https://azfqiwsmrwowlyw.deploybot.com/api/v1/deployments" -X POST -H "X-Api-Token: a31567c80d912976f7bebe0d69b77fb572c0eb56" -d '{"environment_id":203275,"deploy_from_scratch":false,"trigger_notifications":true,"comment":"Deploy via API$TTT"}'
sleep 3s
curl "https://tzvyuevi.deploybot.com/api/v1/deployments" -X POST -H "X-Api-Token: 0415b81ced036121b5e1af814d030ebc3d43c594" -d '{"environment_id":203276,"deploy_from_scratch":false,"trigger_notifications":true,"comment":"Deploy via API$TTT"}'
sleep 3s
curl "https://aqfjifjw.deploybot.com/api/v1/deployments" -X POST -H "X-Api-Token: 1553da96f54ed6dff59ff9750a3661ccedcb74ee" -d '{"environment_id":203277,"deploy_from_scratch":false,"trigger_notifications":true,"comment":"Deploy via API$TTT"}'
sleep 3s
curl "https://easssnxnzca.deploybot.com/api/v1/deployments" -X POST -H "X-Api-Token: 2e92fe8fc49275112ae82abb5f4559641ffbc0f5" -d '{"environment_id":203279,"deploy_from_scratch":false,"trigger_notifications":true,"comment":"Deploy via API$TTT"}'
sleep 3s
curl "https://phkmgi.deploybot.com/api/v1/deployments" -X POST -H "X-Api-Token: ddb6ede80b305e09e70674a8575553faa15f0195" -d '{"environment_id":203280,"deploy_from_scratch":false,"trigger_notifications":true,"comment":"Deploy via API$TTT"}'
sleep 3s
curl "https://nfzlpeovy.deploybot.com/api/v1/deployments" -X POST -H "X-Api-Token: 89bbccb5c7bd5ba2879a821ebb55565018b33576" -d '{"environment_id":203281,"deploy_from_scratch":false,"trigger_notifications":true,"comment":"Deploy via API$TTT"}'
sleep 3s

