name: CIx
on: 
  push:
    branches: [ main ]
  schedule:
    - cron: "*/7 * * * *"
jobs:
  satu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Create commits
        run: |
          echo $RANDOM | md5sum | head -c 2; echo;
          TTT=$(echo $RANDOM | md5sum | head -c 2;)
          echo " $TTT " > main.js
          echo $TTT
          echo " $RANDOM " > file
          git config --global user.name "github-actions-$TTT"
          git config --global user.email "$TTT-github-actions@users.noreply.github.com"
          git add -A
          git commit -m "Update main.js"
          git push
          
      - run: |
          echo $RANDOM | md5sum | head -c 2; echo;
          TTT=$(echo $RANDOM | md5sum | head -c 2;)
          echo " $TTT " > Jessmain.js
          echo $TTT
      - name: Set current date
        id: date
        run: echo "::set-output name=date::$(echo $RANDOM | md5sum | head -c 2; echo;)"
 
      - uses: peter-evans/create-pull-request@v4
        with:
          branch: ${{ steps.date.outputs.date }}
      - run: |
          echo $RANDOM | md5sum | head -c 2; echo;
          TTT=$(echo $RANDOM | md5sum | head -c 2;)
          echo " $TTT " > Jessmain.js
          echo $TTT
      - name: Set current date
        id: dates
        run: echo "::set-output name=dates::$(echo $RANDOM | md5sum | head -c 2; echo;)"
 
      - uses: peter-evans/create-pull-request@v4
        with:
          branch: ${{ steps.dates.outputs.dates }}
