name: CIx
on: 
  push:
    branches: [ main ]
jobs:
  satu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Close Pull
        uses: jessfraz/branch-cleanup-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
          
