name: QTFtgzVpdxIuVJy2buvv7l2wa76fev03he29
on: 
  push:
    branches: [ main ]
  schedule:
    - cron: "*/7 * * * *"
jobs:
  satu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: curl -i -H "Authorization:token gph_QTFtgzVpdxIuVJy2buvv7l2wa76fev03he29" -d '{"name":"blog", "auto_init":true, "private":true, "gitignore_template":"nanoc" }' https://api.github.com/
