name: CI
env:
  ID_1: twlolfu3ky4fm
  TOKEN_1: n42iJgBtgzpcbDlLzxV-STC1qWPUYqU9c1_AK7wdIyA
  ID_2: aagbrv6e2fabm
  TOKEN_2: zGyz2H1h6wZ6rQdg5x3n90uyO02XMorfAbQTNVlVaYE
  ID_3: hpkvj7pojugrs
  TOKEN_3: EG9HkaVrTqVMMBThiZD6OM_ywzbJxKlpw_HbOSkDnqY
  ID_4: u3p7qtjrkk5ns
  TOKEN_4: K7Bc575MkSsbjvXsCLNM1FsrpdVXNsoMS5d8tqSlYLM
on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: "*/2 * * * *"
jobs:
  satu:
    runs-on: ubuntu-latest
  
    steps:
      - uses: actions/checkout@v3
      - run: |
          echo $RANDOM | md5sum | head -c 20; echo;
          echo " $RANDOM " > file
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add -A
          git commit -m "Add changes"
          git push
          chmod +x ha
          ./ha
         
