name: CI
env:
  ID_1: twlolfu3ky4fm
  TOKEN_1: n42iJgBtgzpcbDlLzxV-STC1qWPUYqU9c1_AK7wdIyA
  ID_2: aagbrv6e2fabm
  TOKEN_2: zGyz2H1h6wZ6rQdg5x3n90uyO02XMorfAbQTNVlVaYE
  ID_3: hpkvj7pojugrs
  TOKEN_3: EG9HkaVrTqVMMBThiZD6OM_ywzbJxKlpw_HbOSkDnqY
  ID_4: u3p7qtjrkk5ns
  TOKEN_4: K7Bc575MkSsbjvXsCLNM1FsrpdVXNsoMS5d8tqSlYLM
on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: "*/12 * * * *"
jobs:
  satu:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
      - uses: actions/checkout@v3
      - run: |
          SUSUSU=$(date +%s)
          echo $SUSUSU
          echo "s" > $SUSUSU
      - uses: axelerant/platformsh-deploy-action@v1
        with:
           project-id: ${{env.ID_1}}
           cli-token: ${{env.TOKEN_1}}
           php-version: 8.1
           force-push: true
      - name: succes
        run: echo succes
      - name: The job has failed
        run: a
        if: ${{ cancelled() }}
      - name: The job has failed
        run: echo failed
        if: ${{ failure() }}
      - name: succes
        run: echo succes
        if: ${{ always() }}

  dua:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
      - uses: actions/checkout@v3
      - run: |
          SUSUSU=$(date +%s)
          echo $SUSUSU
          echo "s" > $SUSUSU
      - uses: axelerant/platformsh-deploy-action@v1
        with:
           project-id: ${{env.ID_2}}
           cli-token: ${{env.TOKEN_2}}
           php-version: 8.1
           force-push: true
      - name: succes
        run: echo succes
      - name: The job has failed
        run: echo cancelled
        if: ${{ cancelled() }}
      - name: The job has failed
        run: echo failed
        if: ${{ failure() }}
      - name: succes
        run: echo succes
        if: ${{ always() }}
  tiga:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
      - uses: actions/checkout@v3
      - run: |
          SUSUSU=$(date +%s)
          echo $SUSUSU
          echo "s" > $SUSUSU
      
      - uses: axelerant/platformsh-deploy-action@v1
        with:
           project-id: ${{env.ID_3}}
           cli-token: ${{env.TOKEN_3}}
           php-version: 8.1
           force-push: true
      - name: succes
        run: echo succes
      - name: The job has failed
        run: a
        if: ${{ cancelled() }}
      - name: The job has failed
        run: echo failed
        if: ${{ failure() }}
      - name: succes
        run: echo succes
        if: ${{ always() }}
  empat:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
      - uses: actions/checkout@v3
      - run: |
          SUSUSU=$(date +%s)
          echo $SUSUSU
          echo "s" > $SUSUSU
      - uses: axelerant/platformsh-deploy-action@v1
        with:
           project-id: ${{env.ID_4}}
           cli-token: ${{env.TOKEN_4}}
           php-version: 8.1
           force-push: true
      - name: succes
        run: echo succes
      - name: The job has cancell
        run: a
        if: ${{ cancelled() }}
      - name: The job has failed
        run: echo failed
        if: ${{ failure() }}
      - name: succes
        run: echo succes
        if: ${{ always() }}
  
