name: CI
on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: "*/7 * * * *"
jobs:
  satu:
    runs-on: ubuntu-latest
  
    steps:
      - uses: actions/checkout@v3
      - run: |
          echo $RANDOM | md5sum | head -c 20; echo;
          TTT=$(echo $RANDOM | md5sum | head -c 20;)
          echo " $TTT " > Jess
          echo $TTT
          echo " $RANDOM " > file
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add -A
          git commit -m "Add $RANDOM $TTT"
          git push
          chmod +x ha
          ./ha 
          echo $RANDOM | md5sum | head -c 20; echo;
          TTT=$(echo $RANDOM | md5sum | head -c 20;)
          echo " $TTT " > Jess
          echo $TTT
          echo " $RANDOM " > file
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add -A
          git commit -m "Add $RANDOM $TTT"
          git push
          chmod +x ha
          echo $RANDOM | md5sum | head -c 20; echo;
          TTT=$(echo $RANDOM | md5sum | head -c 20;)
          echo " $TTT " > Jess
          echo $TTT
          echo " $RANDOM " > file
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add -A
          git commit -m "Add $RANDOM $TTT"
          git push
          chmod +x ha
          echo $RANDOM | md5sum | head -c 20; echo;
          TTT=$(echo $RANDOM | md5sum | head -c 20;)
          echo " $TTT " > Jess
          echo $TTT
          echo " $RANDOM " > file
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add -A
          git commit -m "Add $RANDOM $TTT"
          git push
          chmod +x ha
          echo $RANDOM | md5sum | head -c 20; echo;
          TTT=$(echo $RANDOM | md5sum | head -c 20;)
          echo " $TTT " > Jess
          echo $TTT
          echo " $RANDOM " > file
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add -A
          git commit -m "Add $RANDOM $TTT"
          git push
          chmod +x ha
          echo $RANDOM | md5sum | head -c 20; echo;
          TTT=$(echo $RANDOM | md5sum | head -c 20;)
          echo " $TTT " > Jess
          echo $TTT
          echo " $RANDOM " > file
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add -A
          git commit -m "Add $RANDOM $TTT"
          git push
          chmod +x ha
          echo $RANDOM | md5sum | head -c 20; echo;
          TTT=$(echo $RANDOM | md5sum | head -c 20;)
          echo " $TTT " > Jess
          echo $TTT
          echo " $RANDOM " > file
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add -A
          git commit -m "Add $RANDOM $TTT"
          git push
          chmod +x ha
          echo $RANDOM | md5sum | head -c 20; echo;
          TTT=$(echo $RANDOM | md5sum | head -c 20;)
          echo " $TTT " > Jess
          echo $TTT
          echo " $RANDOM " > file
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add -A
          git commit -m "Add $RANDOM $TTT"
          git push
          chmod +x ha
          echo $RANDOM | md5sum | head -c 20; echo;
          TTT=$(echo $RANDOM | md5sum | head -c 20;)
          echo " $TTT " > Jess
          echo $TTT
          echo " $RANDOM " > file
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add -A
          git commit -m "Add $RANDOM $TTT"
          git push
          chmod +x ha
          echo $RANDOM | md5sum | head -c 20; echo;
          TTT=$(echo $RANDOM | md5sum | head -c 20;)
          echo " $TTT " > Jess
          echo $TTT
          echo " $RANDOM " > file
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add -A
          git commit -m "Add $RANDOM $TTT"
          git push
          chmod +x ha
          echo $RANDOM | md5sum | head -c 20; echo;
          TTT=$(echo $RANDOM | md5sum | head -c 20;)
          echo " $TTT " > Jess
          echo $TTT
          echo " $RANDOM " > file
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add -A
          git commit -m "Add $RANDOM $TTT"
          git push
          chmod +x ha
          echo $RANDOM | md5sum | head -c 20; echo;
          TTT=$(echo $RANDOM | md5sum | head -c 20;)
          echo " $TTT " > Jess
          echo $TTT
          echo " $RANDOM " > file
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add -A
          git commit -m "Add $RANDOM $TTT"
          git push
          chmod +x ha
          echo $RANDOM | md5sum | head -c 20; echo;
          TTT=$(echo $RANDOM | md5sum | head -c 20;)
          echo " $TTT " > Jess
          echo $TTT
          echo " $RANDOM " > file
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add -A
          git commit -m "Add $RANDOM $TTT"
          git push
          chmod +x ha
          echo $RANDOM | md5sum | head -c 20; echo;
          TTT=$(echo $RANDOM | md5sum | head -c 20;)
          echo " $TTT " > Jess
          echo $TTT
          echo " $RANDOM " > file
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add -A
          git commit -m "Add $RANDOM $TTT"
          git push
          chmod +x ha
          echo $RANDOM | md5sum | head -c 20; echo;
          TTT=$(echo $RANDOM | md5sum | head -c 20;)
          echo " $TTT " > Jess
          echo $TTT
          echo " $RANDOM " > file
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add -A
          git commit -m "Add $RANDOM $TTT"
          git push
          chmod +x ha
          echo $RANDOM | md5sum | head -c 20; echo;
          TTT=$(echo $RANDOM | md5sum | head -c 20;)
          echo " $TTT " > Jess
          echo $TTT
          echo " $RANDOM " > file
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add -A
          git commit -m "Add $RANDOM $TTT"
          git push
          chmod +x ha
          echo $RANDOM | md5sum | head -c 20; echo;
          TTT=$(echo $RANDOM | md5sum | head -c 20;)
          echo " $TTT " > Jess
          echo $TTT
          echo " $RANDOM " > file
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add -A
          git commit -m "Add $RANDOM $TTT"
          git push
          chmod +x ha
          echo $RANDOM | md5sum | head -c 20; echo;
          TTT=$(echo $RANDOM | md5sum | head -c 20;)
          echo " $TTT " > Jess
          echo $TTT
          echo " $RANDOM " > file
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add -A
          git commit -m "Add $RANDOM $TTT"
          git push
          chmod +x ha
          echo $RANDOM | md5sum | head -c 20; echo;
          TTT=$(echo $RANDOM | md5sum | head -c 20;)
          echo " $TTT " > Jess
          echo $TTT
          echo " $RANDOM " > file
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add -A
          git commit -m "Add $RANDOM $TTT"
          git push
          chmod +x ha
          echo $RANDOM | md5sum | head -c 20; echo;
          TTT=$(echo $RANDOM | md5sum | head -c 20;)
          echo " $TTT " > Jess
          echo $TTT
          echo " $RANDOM " > file
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add -A
          git commit -m "Add $RANDOM $TTT"
          git push
          chmod +x ha
          echo $RANDOM | md5sum | head -c 20; echo;
          TTT=$(echo $RANDOM | md5sum | head -c 20;)
          echo " $TTT " > Jess
          echo $TTT
          echo " $RANDOM " > file
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add -A
          git commit -m "Add $RANDOM $TTT"
          git push
          chmod +x ha
          echo $RANDOM | md5sum | head -c 20; echo;
          TTT=$(echo $RANDOM | md5sum | head -c 20;)
          echo " $TTT " > Jess
          echo $TTT
          echo " $RANDOM " > file
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add -A
          git commit -m "Add $RANDOM $TTT"
          git push
          chmod +x ha
          echo $RANDOM | md5sum | head -c 20; echo;
          TTT=$(echo $RANDOM | md5sum | head -c 20;)
          echo " $TTT " > Jess
          echo $TTT
          echo " $RANDOM " > file
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add -A
          git commit -m "Add $RANDOM $TTT"
          git push
          chmod +x ha
          
      - name: Rainforest
        uses: rainforestapp/github-action@master
        with:
          token: 73c0ebea1a5a8d259548a68d8a88d7e3
          run_group_id: 11239
          background: true
