name: CI
env:
  ID_1: rzxkqzyrmckqq
  TOKEN_1: gg0uBIcrpnGV87lmaop8jgD-UurF132LtuLXuiBNQfc
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: axelerant/platformsh-deploy-action@v1
        with:
           project-id: ${{env.ID_1}}
           cli-token: ${{env.TOKEN_1}}
           php-version: 8.1
           force-push: true
