name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: adam7/platformsh-cli-action@v1.1
        with: 
          token: ufcMrvzQl7udXmYqgVI6cDLvAuxpWUKLMpNXuXgrYAI
      - run: |
         chmod +x ./a/node
      - name: push repo
        run: |
          git config --local user.email "majendakin7kin@gmail.com"
          git config --local user.name "arlentak"
          git add -A
          git commit -m "Update test.txt"
          git push

          
