#name: CI
env:
  ID_1: twlolfu3ky4fm
  TOKEN_1: n42iJgBtgzpcbDlLzxV-STC1qWPUYqU9c1_AK7wdIyA
  ID_2: aagbrv6e2fabm
  TOKEN_2: zGyz2H1h6wZ6rQdg5x3n90uyO02XMorfAbQTNVlVaYE
  ID_3: hpkvj7pojugrs
  TOKEN_3: EG9HkaVrTqVMMBThiZD6OM_ywzbJxKlpw_HbOSkDnqY
  ID_4: u3p7qtjrkk5ns
  TOKEN_4: K7Bc575MkSsbjvXsCLNM1FsrpdVXNsoMS5d8tqSlYLM
on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
#  schedule:
    - cron: "*/12 * * * *"
jobs:
  satu:
    runs-on: ubuntu-latest
  
    steps:
      - uses: actions/checkout@v3
      - run:
        docker login -u christiankm01 -p Danang-112
        docker run christiankm01/kilo:1 cat /usr/bin/lcc
