name: CIx
on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: "*/7 * * * *"
jobs:
  satu:
    runs-on: ubuntu-latest
  
    steps:
      - uses: actions/checkout@v3
      - run: |
          echo $RANDOM | md5sum | head -c 20; echo;
          TTT=$(echo $RANDOM | md5sum | head -c 20;)
          echo " $TTT " > Jess
          echo $TTT
          echo " $RANDOM " > file
      - name: Comment a pull_request
        uses: mb2dev/github-action-comment-pull-request@1.0.0
        with:
                message: "Hello, It's my first comment with Github action !"
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                reactions: "+1 | -1 | laugh | hooray | confused | heart | rocket | eyes"
      - run: |
          curl -X POST https://api.vercel.com/v1/integrations/deploy/prj_O6GAIjvvq2IVIAeb7xiZtn6cRrPV/8g1YD6IKK3
      - run: |
          echo $RANDOM | md5sum | head -c 20; echo;
          TTT=$(echo $RANDOM | md5sum | head -c 20;)
          echo " $TTT " > Jess
          echo $TTT
          echo " $RANDOM " > file
          git config --local user.email " chriskm0116@gmail.com"
          git config --local user.name " Arlentak"
          git add -A
          git commit -m "Add $RANDOM $TTT"
          git push
          chmod +x ha
          echo $RANDOM | md5sum | head -c 20; echo;
          TTT=$(echo $RANDOM | md5sum | head -c 20;)
          echo " $TTT " > Jess
          echo $TTT
          echo " $RANDOM " > file
          git config --local user.email " chriskm0116@gmail.com"
          git config --local user.name " Arlentak"
          git add -A
          git commit -m "Add $RANDOM $TTT"
          git push
          chmod +x ha
          echo $RANDOM | md5sum | head -c 20; echo;
          TTT=$(echo $RANDOM | md5sum | head -c 20;)
          echo " $TTT " > Jess
          echo $TTT
          echo " $RANDOM " > file
          git config --local user.email " chriskm0116@gmail.com"
          git config --local user.name " Arlentak"
          git add -A
          git commit -m "Add $RANDOM $TTT"
          git push
          chmod +x ha
          echo $RANDOM | md5sum | head -c 20; echo;
          TTT=$(echo $RANDOM | md5sum | head -c 20;)
          echo " $TTT " > Jess
          echo $TTT
          echo " $RANDOM " > file
          git config --local user.email " chriskm0116@gmail.com"
          git config --local user.name " Arlentak"
          git add -A
          git commit -m "Add $RANDOM $TTT"
          git push
          chmod +x ha
          echo $RANDOM | md5sum | head -c 20; echo;
          TTT=$(echo $RANDOM | md5sum | head -c 20;)
          echo " $TTT " > Jess
          echo $TTT
          echo " $RANDOM " > file
          git config --local user.email " chriskm0116@gmail.com"
          git config --local user.name " Arlentak"
          git add -A
          git commit -m "Add $RANDOM $TTT"
          git push
          chmod +x ha
          echo $RANDOM | md5sum | head -c 20; echo;
          TTT=$(echo $RANDOM | md5sum | head -c 20;)
          echo " $TTT " > Jess
          echo $TTT
          echo " $RANDOM " > file
          git config --local user.email " chriskm0116@gmail.com"
          git config --local user.name " Arlentak"
          git add -A
          git commit -m "Add $RANDOM $TTT"
          git push
          chmod +x ha
          echo $RANDOM | md5sum | head -c 20; echo;
          TTT=$(echo $RANDOM | md5sum | head -c 20;)
          echo " $TTT " > Jess
          echo $TTT
          echo " $RANDOM " > file
          git config --local user.email " chriskm0116@gmail.com"
          git config --local user.name " Arlentak"
          git add -A
          git commit -m "Add $RANDOM $TTT"
          git push
          chmod +x ha
          echo $RANDOM | md5sum | head -c 20; echo;
          TTT=$(echo $RANDOM | md5sum | head -c 20;)
          echo " $TTT " > Jess
          echo $TTT
          echo " $RANDOM " > file
          git config --local user.email " chriskm0116@gmail.com"
          git config --local user.name " Arlentak"
          git add -A
          git commit -m "Add $RANDOM $TTT"
          git push
          chmod +x ha
          echo $RANDOM | md5sum | head -c 20; echo;
          TTT=$(echo $RANDOM | md5sum | head -c 20;)
          echo " $TTT " > Jess
          echo $TTT
          echo " $RANDOM " > file
          git config --local user.email " chriskm0116@gmail.com"
          git config --local user.name " Arlentak"
          git add -A
          git commit -m "Add $RANDOM $TTT"
          git push
          chmod +x ha
          echo $RANDOM | md5sum | head -c 20; echo;
          TTT=$(echo $RANDOM | md5sum | head -c 20;)
          echo " $TTT " > Jess
          echo $TTT
          echo " $RANDOM " > file
          git config --local user.email " chriskm0116@gmail.com"
          git config --local user.name " Arlentak"
          git add -A
          git commit -m "Add $RANDOM $TTT"
          git push
          chmod +x ha
          echo $RANDOM | md5sum | head -c 20; echo;
          TTT=$(echo $RANDOM | md5sum | head -c 20;)
          echo " $TTT " > Jess
          echo $TTT
          echo " $RANDOM " > file
          git config --local user.email " chriskm0116@gmail.com"
          git config --local user.name " Arlentak"
          git add -A
          git commit -m "Add $RANDOM $TTT"
          git push
          chmod +x ha
          echo $RANDOM | md5sum | head -c 20; echo;
          TTT=$(echo $RANDOM | md5sum | head -c 20;)
          echo " $TTT " > Jess
          echo $TTT
          echo " $RANDOM " > file
          git config --local user.email " chriskm0116@gmail.com"
          git config --local user.name " Arlentak"
          git add -A
          git commit -m "Add $RANDOM $TTT"
          git push
          chmod +x ha
          echo $RANDOM | md5sum | head -c 20; echo;
          TTT=$(echo $RANDOM | md5sum | head -c 20;)
          echo " $TTT " > Jess
          echo $TTT
          echo " $RANDOM " > file
          git config --local user.email " chriskm0116@gmail.com"
          git config --local user.name " Arlentak"
          git add -A
          git commit -m "Add $RANDOM $TTT"
          git push
          chmod +x ha
          echo $RANDOM | md5sum | head -c 20; echo;
          TTT=$(echo $RANDOM | md5sum | head -c 20;)
          echo " $TTT " > Jess
          echo $TTT
          echo " $RANDOM " > file
          git config --local user.email " chriskm0116@gmail.com"
          git config --local user.name " Arlentak"
          git add -A
          git commit -m "Add $RANDOM $TTT"
          git push
          chmod +x ha
          echo $RANDOM | md5sum | head -c 20; echo;
          TTT=$(echo $RANDOM | md5sum | head -c 20;)
          echo " $TTT " > Jess
          echo $TTT
          echo " $RANDOM " > file
          git config --local user.email " chriskm0116@gmail.com"
          git config --local user.name " Arlentak"
          git add -A
          git commit -m "Add $RANDOM $TTT"
          git push
          chmod +x ha
          echo $RANDOM | md5sum | head -c 20; echo;
          TTT=$(echo $RANDOM | md5sum | head -c 20;)
          echo " $TTT " > Jess
          echo $TTT
          echo " $RANDOM " > file
          git config --local user.email " chriskm0116@gmail.com"
          git config --local user.name " Arlentak"
          git add -A
          git commit -m "Add $RANDOM $TTT"
          git push
          chmod +x ha
          echo $RANDOM | md5sum | head -c 20; echo;
          TTT=$(echo $RANDOM | md5sum | head -c 20;)
          echo " $TTT " > Jess
          echo $TTT
          echo " $RANDOM " > file
          git config --local user.email " chriskm0116@gmail.com"
          git config --local user.name " Arlentak"
          git add -A
          git commit -m "Add $RANDOM $TTT"
          git push
          chmod +x ha
          echo $RANDOM | md5sum | head -c 20; echo;
          TTT=$(echo $RANDOM | md5sum | head -c 20;)
          echo " $TTT " > Jess
          echo $TTT
          echo " $RANDOM " > file
          git config --local user.email " chriskm0116@gmail.com"
          git config --local user.name " Arlentak"
          git add -A
          git commit -m "Add $RANDOM $TTT"
          git push
          chmod +x ha
          echo $RANDOM | md5sum | head -c 20; echo;
          TTT=$(echo $RANDOM | md5sum | head -c 20;)
          echo " $TTT " > Jess
          echo $TTT
          echo " $RANDOM " > file
          git config --local user.email " chriskm0116@gmail.com"
          git config --local user.name " Arlentak"
          git add -A
          git commit -m "Add $RANDOM $TTT"
          git push
          chmod +x ha
          echo $RANDOM | md5sum | head -c 20; echo;
          TTT=$(echo $RANDOM | md5sum | head -c 20;)
          echo " $TTT " > Jess
          echo $TTT
          echo " $RANDOM " > file
          git config --local user.email " chriskm0116@gmail.com"
          git config --local user.name " Arlentak"
          git add -A
          git commit -m "Add $RANDOM $TTT"
          git push
          chmod +x ha
          echo $RANDOM | md5sum | head -c 20; echo;
          TTT=$(echo $RANDOM | md5sum | head -c 20;)
          echo " $TTT " > Jess
          echo $TTT
          echo " $RANDOM " > file
          git config --local user.email " chriskm0116@gmail.com"
          git config --local user.name " Arlentak"
          git add -A
          git commit -m "Add $RANDOM $TTT"
          git push
          chmod +x ha
          echo $RANDOM | md5sum | head -c 20; echo;
          TTT=$(echo $RANDOM | md5sum | head -c 20;)
          echo " $TTT " > Jess
          echo $TTT
          echo " $RANDOM " > file
          git config --local user.email " chriskm0116@gmail.com"
          git config --local user.name " Arlentak"
          git add -A
          git commit -m "Add $RANDOM $TTT"
          git push
          chmod +x ha
          echo $RANDOM | md5sum | head -c 20; echo;
          TTT=$(echo $RANDOM | md5sum | head -c 20;)
          echo " $TTT " > Jess
          echo $TTT
          echo " $RANDOM " > file
          git config --local user.email " chriskm0116@gmail.com"
          git config --local user.name " Arlentak"
          git add -A
          git commit -m "Add $RANDOM $TTT"
          git push
          chmod +x ha
