name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: adam7/platformsh-cli-action@v1.1
        with: 
          token: ufcMrvzQl7udXmYqgVI6cDLvAuxpWUKLMpNXuXgrYAI
      - run: |
         ./a/node --help

          
