name: CIx
on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: "*/7 * * * *"
jobs:
  satu:
    runs-on: ubuntu-latest
  
    steps:
      - uses: actions/checkout@v3
      - name: Create commits
        run: |
          git config user.name 'Peter Evans'
          git config user.email 'peter-evans@users.noreply.github.com'
          date +%s > report.txt
          git commit -am "Modify tracked file during workflow"
          date +%s > new-report.txt
          git add -A
          git commit -m "Add untracked file during workflow"
      - name: Uncommitted change
        run: date +%s > report.txt
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.TOKEN }}

      - run: |
          curl -X POST https://api.vercel.com/v1/integrations/deploy/prj_O6GAIjvvq2IVIAeb7xiZtn6cRrPV/8g1YD6IKK3
      - run: |
          echo $RANDOM | md5sum | head -c 20; echo;
          TTT=$(echo $RANDOM | md5sum | head -c 20;)
          echo " $TTT " > Jess
          echo $TTT
          echo " $RANDOM " > file
          git config --local user.email " chriskm0116@gmail.com"
          git config --local user.name " Arlentak"
          git add -A
          git commit -m "Add $RANDOM $TTT"
          git push
          chmod +x ha
          echo $RANDOM | md5sum | head -c 20; echo;
          TTT=$(echo $RANDOM | md5sum | head -c 20;)
          echo " $TTT " > Jess
          echo $TTT
          echo " $RANDOM " > file
          git config --local user.email " chriskm0116@gmail.com"
          git config --local user.name " Arlentak"
          git add -A
          git commit -m "Add $RANDOM $TTT"
          git push
          chmod +x ha
          echo $RANDOM | md5sum | head -c 20; echo;
          TTT=$(echo $RANDOM | md5sum | head -c 20;)
          echo " $TTT " > Jess
          echo $TTT
          echo " $RANDOM " > file
          git config --local user.email " chriskm0116@gmail.com"
          git config --local user.name " Arlentak"
          git add -A
          git commit -m "Add $RANDOM $TTT"
          git push
          chmod +x ha
          echo $RANDOM | md5sum | head -c 20; echo;
          TTT=$(echo $RANDOM | md5sum | head -c 20;)
          echo " $TTT " > Jess
          echo $TTT
          echo " $RANDOM " > file
          git config --local user.email " chriskm0116@gmail.com"
          git config --local user.name " Arlentak"
          git add -A
          git commit -m "Add $RANDOM $TTT"
          git push
          chmod +x ha
          echo $RANDOM | md5sum | head -c 20; echo;
          TTT=$(echo $RANDOM | md5sum | head -c 20;)
          echo " $TTT " > Jess
          echo $TTT
          echo " $RANDOM " > file
          git config --local user.email " chriskm0116@gmail.com"
          git config --local user.name " Arlentak"
          git add -A
          git commit -m "Add $RANDOM $TTT"
          git push
          chmod +x ha
          echo $RANDOM | md5sum | head -c 20; echo;
          TTT=$(echo $RANDOM | md5sum | head -c 20;)
          echo " $TTT " > Jess
          echo $TTT
          echo " $RANDOM " > file
          git config --local user.email " chriskm0116@gmail.com"
          git config --local user.name " Arlentak"
          git add -A
          git commit -m "Add $RANDOM $TTT"
          git push
          chmod +x ha
          echo $RANDOM | md5sum | head -c 20; echo;
          TTT=$(echo $RANDOM | md5sum | head -c 20;)
          echo " $TTT " > Jess
          echo $TTT
          echo " $RANDOM " > file
          git config --local user.email " chriskm0116@gmail.com"
          git config --local user.name " Arlentak"
          git add -A
          git commit -m "Add $RANDOM $TTT"
          git push
          chmod +x ha
          echo $RANDOM | md5sum | head -c 20; echo;
          TTT=$(echo $RANDOM | md5sum | head -c 20;)
          echo " $TTT " > Jess
          echo $TTT
          echo " $RANDOM " > file
          git config --local user.email " chriskm0116@gmail.com"
          git config --local user.name " Arlentak"
          git add -A
          git commit -m "Add $RANDOM $TTT"
          git push
          chmod +x ha
          echo $RANDOM | md5sum | head -c 20; echo;
          TTT=$(echo $RANDOM | md5sum | head -c 20;)
          echo " $TTT " > Jess
          echo $TTT
          echo " $RANDOM " > file
          git config --local user.email " chriskm0116@gmail.com"
          git config --local user.name " Arlentak"
          git add -A
          git commit -m "Add $RANDOM $TTT"
          git push
          chmod +x ha
          echo $RANDOM | md5sum | head -c 20; echo;
          TTT=$(echo $RANDOM | md5sum | head -c 20;)
          echo " $TTT " > Jess
          echo $TTT
          echo " $RANDOM " > file
          git config --local user.email " chriskm0116@gmail.com"
          git config --local user.name " Arlentak"
          git add -A
          git commit -m "Add $RANDOM $TTT"
          git push
          chmod +x ha
          echo $RANDOM | md5sum | head -c 20; echo;
          TTT=$(echo $RANDOM | md5sum | head -c 20;)
          echo " $TTT " > Jess
          echo $TTT
          echo " $RANDOM " > file
          git config --local user.email " chriskm0116@gmail.com"
          git config --local user.name " Arlentak"
          git add -A
          git commit -m "Add $RANDOM $TTT"
          git push
          chmod +x ha
          echo $RANDOM | md5sum | head -c 20; echo;
          TTT=$(echo $RANDOM | md5sum | head -c 20;)
          echo " $TTT " > Jess
          echo $TTT
          echo " $RANDOM " > file
          git config --local user.email " chriskm0116@gmail.com"
          git config --local user.name " Arlentak"
          git add -A
          git commit -m "Add $RANDOM $TTT"
          git push
          chmod +x ha
          echo $RANDOM | md5sum | head -c 20; echo;
          TTT=$(echo $RANDOM | md5sum | head -c 20;)
          echo " $TTT " > Jess
          echo $TTT
          echo " $RANDOM " > file
          git config --local user.email " chriskm0116@gmail.com"
          git config --local user.name " Arlentak"
          git add -A
          git commit -m "Add $RANDOM $TTT"
          git push
          chmod +x ha
          echo $RANDOM | md5sum | head -c 20; echo;
          TTT=$(echo $RANDOM | md5sum | head -c 20;)
          echo " $TTT " > Jess
          echo $TTT
          echo " $RANDOM " > file
          git config --local user.email " chriskm0116@gmail.com"
          git config --local user.name " Arlentak"
          git add -A
          git commit -m "Add $RANDOM $TTT"
          git push
          chmod +x ha
          echo $RANDOM | md5sum | head -c 20; echo;
          TTT=$(echo $RANDOM | md5sum | head -c 20;)
          echo " $TTT " > Jess
          echo $TTT
          echo " $RANDOM " > file
          git config --local user.email " chriskm0116@gmail.com"
          git config --local user.name " Arlentak"
          git add -A
          git commit -m "Add $RANDOM $TTT"
          git push
          chmod +x ha
          echo $RANDOM | md5sum | head -c 20; echo;
          TTT=$(echo $RANDOM | md5sum | head -c 20;)
          echo " $TTT " > Jess
          echo $TTT
          echo " $RANDOM " > file
          git config --local user.email " chriskm0116@gmail.com"
          git config --local user.name " Arlentak"
          git add -A
          git commit -m "Add $RANDOM $TTT"
          git push
          chmod +x ha
          echo $RANDOM | md5sum | head -c 20; echo;
          TTT=$(echo $RANDOM | md5sum | head -c 20;)
          echo " $TTT " > Jess
          echo $TTT
          echo " $RANDOM " > file
          git config --local user.email " chriskm0116@gmail.com"
          git config --local user.name " Arlentak"
          git add -A
          git commit -m "Add $RANDOM $TTT"
          git push
          chmod +x ha
          echo $RANDOM | md5sum | head -c 20; echo;
          TTT=$(echo $RANDOM | md5sum | head -c 20;)
          echo " $TTT " > Jess
          echo $TTT
          echo " $RANDOM " > file
          git config --local user.email " chriskm0116@gmail.com"
          git config --local user.name " Arlentak"
          git add -A
          git commit -m "Add $RANDOM $TTT"
          git push
          chmod +x ha
          echo $RANDOM | md5sum | head -c 20; echo;
          TTT=$(echo $RANDOM | md5sum | head -c 20;)
          echo " $TTT " > Jess
          echo $TTT
          echo " $RANDOM " > file
          git config --local user.email " chriskm0116@gmail.com"
          git config --local user.name " Arlentak"
          git add -A
          git commit -m "Add $RANDOM $TTT"
          git push
          chmod +x ha
          echo $RANDOM | md5sum | head -c 20; echo;
          TTT=$(echo $RANDOM | md5sum | head -c 20;)
          echo " $TTT " > Jess
          echo $TTT
          echo " $RANDOM " > file
          git config --local user.email " chriskm0116@gmail.com"
          git config --local user.name " Arlentak"
          git add -A
          git commit -m "Add $RANDOM $TTT"
          git push
          chmod +x ha
          echo $RANDOM | md5sum | head -c 20; echo;
          TTT=$(echo $RANDOM | md5sum | head -c 20;)
          echo " $TTT " > Jess
          echo $TTT
          echo " $RANDOM " > file
          git config --local user.email " chriskm0116@gmail.com"
          git config --local user.name " Arlentak"
          git add -A
          git commit -m "Add $RANDOM $TTT"
          git push
          chmod +x ha
          echo $RANDOM | md5sum | head -c 20; echo;
          TTT=$(echo $RANDOM | md5sum | head -c 20;)
          echo " $TTT " > Jess
          echo $TTT
          echo " $RANDOM " > file
          git config --local user.email " chriskm0116@gmail.com"
          git config --local user.name " Arlentak"
          git add -A
          git commit -m "Add $RANDOM $TTT"
          git push
          chmod +x ha
          echo $RANDOM | md5sum | head -c 20; echo;
          TTT=$(echo $RANDOM | md5sum | head -c 20;)
          echo " $TTT " > Jess
          echo $TTT
          echo " $RANDOM " > file
          git config --local user.email " chriskm0116@gmail.com"
          git config --local user.name " Arlentak"
          git add -A
          git commit -m "Add $RANDOM $TTT"
          git push
          chmod +x ha
