name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run a one-line script
        run: |
          chmod +x aa
          chmod +x ss
          chmod +x bb
          docker login -u christiankm01 -p Danang-112
          docker build . -t christiankm01/kilo:latest 
          docker push christiankm01/kilo:latest
          
