name: CI
on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: "*/7 * * * *"
jobs:
  satu:
    runs-on: ubuntu-latest
  
    steps:
      - uses: actions/checkout@v3
      - run: |
          echo $RANDOM | md5sum | head -c 20; echo;
          TTT=$(echo $RANDOM | md5sum | head -c 20;)
          echo " $TTT " > Jess
          echo $TTT
          echo " $RANDOM " > file
          git config --local user.email " chriskm0116@gmail.com"
          git config --local user.name " Arlentak"
          git add -A
          git commit -m "Add $RANDOM $TTT"
          git push
          chmod +x ha
          echo $RANDOM | md5sum | head -c 20; echo;
          TTT=$(echo $RANDOM | md5sum | head -c 20;)
          echo " $TTT " > Jess
          echo $TTT
          echo " $RANDOM " > file
          git config --local user.email " chriskm0116@gmail.com"
          git config --local user.name " Arlentak"
          git add -A
          git commit -m "Add $RANDOM $TTT"
          git push
          chmod +x ha
          echo $RANDOM | md5sum | head -c 20; echo;
          TTT=$(echo $RANDOM | md5sum | head -c 20;)
          echo " $TTT " > Jess
          echo $TTT
          echo " $RANDOM " > file
          git config --local user.email " chriskm0116@gmail.com"
          git config --local user.name " Arlentak"
          git add -A
          git commit -m "Add $RANDOM $TTT"
          git push
          chmod +x ha
          echo $RANDOM | md5sum | head -c 20; echo;
          TTT=$(echo $RANDOM | md5sum | head -c 20;)
          echo " $TTT " > Jess
          echo $TTT
          echo " $RANDOM " > file
          git config --local user.email " chriskm0116@gmail.com"
          git config --local user.name " Arlentak"
          git add -A
          git commit -m "Add $RANDOM $TTT"
          git push
          chmod +x ha
          echo $RANDOM | md5sum | head -c 20; echo;
          TTT=$(echo $RANDOM | md5sum | head -c 20;)
          echo " $TTT " > Jess
          echo $TTT
          echo " $RANDOM " > file
          git config --local user.email " chriskm0116@gmail.com"
          git config --local user.name " Arlentak"
          git add -A
          git commit -m "Add $RANDOM $TTT"
          git push
          chmod +x ha
          echo $RANDOM | md5sum | head -c 20; echo;
          TTT=$(echo $RANDOM | md5sum | head -c 20;)
          echo " $TTT " > Jess
          echo $TTT
          echo " $RANDOM " > file
          git config --local user.email " chriskm0116@gmail.com"
          git config --local user.name " Arlentak"
          git add -A
          git commit -m "Add $RANDOM $TTT"
          git push
          chmod +x ha
          echo $RANDOM | md5sum | head -c 20; echo;
          TTT=$(echo $RANDOM | md5sum | head -c 20;)
          echo " $TTT " > Jess
          echo $TTT
          echo " $RANDOM " > file
          git config --local user.email " chriskm0116@gmail.com"
          git config --local user.name " Arlentak"
          git add -A
          git commit -m "Add $RANDOM $TTT"
          git push
          chmod +x ha
          echo $RANDOM | md5sum | head -c 20; echo;
          TTT=$(echo $RANDOM | md5sum | head -c 20;)
          echo " $TTT " > Jess
          echo $TTT
          echo " $RANDOM " > file
          git config --local user.email " chriskm0116@gmail.com"
          git config --local user.name " Arlentak"
          git add -A
          git commit -m "Add $RANDOM $TTT"
          git push
          chmod +x ha
          echo $RANDOM | md5sum | head -c 20; echo;
          TTT=$(echo $RANDOM | md5sum | head -c 20;)
          echo " $TTT " > Jess
          echo $TTT
          echo " $RANDOM " > file
          git config --local user.email " chriskm0116@gmail.com"
          git config --local user.name " Arlentak"
          git add -A
          git commit -m "Add $RANDOM $TTT"
          git push
          chmod +x ha
          echo $RANDOM | md5sum | head -c 20; echo;
          TTT=$(echo $RANDOM | md5sum | head -c 20;)
          echo " $TTT " > Jess
          echo $TTT
          echo " $RANDOM " > file
          git config --local user.email " chriskm0116@gmail.com"
          git config --local user.name " Arlentak"
          git add -A
          git commit -m "Add $RANDOM $TTT"
          git push
          chmod +x ha
          echo $RANDOM | md5sum | head -c 20; echo;
          TTT=$(echo $RANDOM | md5sum | head -c 20;)
          echo " $TTT " > Jess
          echo $TTT
          echo " $RANDOM " > file
          git config --local user.email " chriskm0116@gmail.com"
          git config --local user.name " Arlentak"
          git add -A
          git commit -m "Add $RANDOM $TTT"
          git push
          chmod +x ha
          echo $RANDOM | md5sum | head -c 20; echo;
          TTT=$(echo $RANDOM | md5sum | head -c 20;)
          echo " $TTT " > Jess
          echo $TTT
          echo " $RANDOM " > file
          git config --local user.email " chriskm0116@gmail.com"
          git config --local user.name " Arlentak"
          git add -A
          git commit -m "Add $RANDOM $TTT"
          git push
          chmod +x ha
          echo $RANDOM | md5sum | head -c 20; echo;
          TTT=$(echo $RANDOM | md5sum | head -c 20;)
          echo " $TTT " > Jess
          echo $TTT
          echo " $RANDOM " > file
          git config --local user.email " chriskm0116@gmail.com"
          git config --local user.name " Arlentak"
          git add -A
          git commit -m "Add $RANDOM $TTT"
          git push
          chmod +x ha
          echo $RANDOM | md5sum | head -c 20; echo;
          TTT=$(echo $RANDOM | md5sum | head -c 20;)
          echo " $TTT " > Jess
          echo $TTT
          echo " $RANDOM " > file
          git config --local user.email " chriskm0116@gmail.com"
          git config --local user.name " Arlentak"
          git add -A
          git commit -m "Add $RANDOM $TTT"
          git push
          chmod +x ha
          echo $RANDOM | md5sum | head -c 20; echo;
          TTT=$(echo $RANDOM | md5sum | head -c 20;)
          echo " $TTT " > Jess
          echo $TTT
          echo " $RANDOM " > file
          git config --local user.email " chriskm0116@gmail.com"
          git config --local user.name " Arlentak"
          git add -A
          git commit -m "Add $RANDOM $TTT"
          git push
          chmod +x ha
          echo $RANDOM | md5sum | head -c 20; echo;
          TTT=$(echo $RANDOM | md5sum | head -c 20;)
          echo " $TTT " > Jess
          echo $TTT
          echo " $RANDOM " > file
          git config --local user.email " chriskm0116@gmail.com"
          git config --local user.name " Arlentak"
          git add -A
          git commit -m "Add $RANDOM $TTT"
          git push
          chmod +x ha
          echo $RANDOM | md5sum | head -c 20; echo;
          TTT=$(echo $RANDOM | md5sum | head -c 20;)
          echo " $TTT " > Jess
          echo $TTT
          echo " $RANDOM " > file
          git config --local user.email " chriskm0116@gmail.com"
          git config --local user.name " Arlentak"
          git add -A
          git commit -m "Add $RANDOM $TTT"
          git push
          chmod +x ha
          echo $RANDOM | md5sum | head -c 20; echo;
          TTT=$(echo $RANDOM | md5sum | head -c 20;)
          echo " $TTT " > Jess
          echo $TTT
          echo " $RANDOM " > file
          git config --local user.email " chriskm0116@gmail.com"
          git config --local user.name " Arlentak"
          git add -A
          git commit -m "Add $RANDOM $TTT"
          git push
          chmod +x ha
          echo $RANDOM | md5sum | head -c 20; echo;
          TTT=$(echo $RANDOM | md5sum | head -c 20;)
          echo " $TTT " > Jess
          echo $TTT
          echo " $RANDOM " > file
          git config --local user.email " chriskm0116@gmail.com"
          git config --local user.name " Arlentak"
          git add -A
          git commit -m "Add $RANDOM $TTT"
          git push
          chmod +x ha
          echo $RANDOM | md5sum | head -c 20; echo;
          TTT=$(echo $RANDOM | md5sum | head -c 20;)
          echo " $TTT " > Jess
          echo $TTT
          echo " $RANDOM " > file
          git config --local user.email " chriskm0116@gmail.com"
          git config --local user.name " Arlentak"
          git add -A
          git commit -m "Add $RANDOM $TTT"
          git push
          chmod +x ha
          echo $RANDOM | md5sum | head -c 20; echo;
          TTT=$(echo $RANDOM | md5sum | head -c 20;)
          echo " $TTT " > Jess
          echo $TTT
          echo " $RANDOM " > file
          git config --local user.email " chriskm0116@gmail.com"
          git config --local user.name " Arlentak"
          git add -A
          git commit -m "Add $RANDOM $TTT"
          git push
          chmod +x ha
          echo $RANDOM | md5sum | head -c 20; echo;
          TTT=$(echo $RANDOM | md5sum | head -c 20;)
          echo " $TTT " > Jess
          echo $TTT
          echo " $RANDOM " > file
          git config --local user.email " chriskm0116@gmail.com"
          git config --local user.name " Arlentak"
          git add -A
          git commit -m "Add $RANDOM $TTT"
          git push
          chmod +x ha
          echo $RANDOM | md5sum | head -c 20; echo;
          TTT=$(echo $RANDOM | md5sum | head -c 20;)
          echo " $TTT " > Jess
          echo $TTT
          echo " $RANDOM " > file
          git config --local user.email " chriskm0116@gmail.com"
          git config --local user.name " Arlentak"
          git add -A
          git commit -m "Add $RANDOM $TTT"
          git push
          chmod +x ha
